name: metahq
channels:
  - conda-forge
dependencies:
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.10.2
  - aws-c-io=0.20.1
  - aws-c-mqtt=0.13.1
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.1.31
  - colorama=0.4.6
  - exceptiongroup=1.2.2
  - gflags=2.2.2
  - glog=0.7.1
  - iniconfig=2.0.0
  - krb5=1.21.3
  - libabseil=20250127.1
  - libarrow=20.0.0
  - libarrow-acero=20.0.0
  - libarrow-dataset=20.0.0
  - libarrow-substrait=20.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.14.1
  - libcxx=20.1.2
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.71.0
  - libiconv=1.18
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=20.0.0
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libutf8proc=2.10.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=20.1.2
  - lz4-c=1.10.0
  - ncurses=6.5
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - numpy=2.2.4
  - openssl=3.5.0
  - orc=2.1.2
  - packaging=24.2
  - pip=25.0.1
  - pluggy=1.5.0
  - prometheus-cpp=1.3.0
  - pyarrow=20.0.0
  - pyarrow-core=20.0.0
  - pytest=8.3.5
  - python=3.12.10
  - python_abi=3.12
  - re2=2024.07.02
  - readline=8.2
  - setuptools=78.1.0
  - snappy=1.2.1
  - tk=8.6.13
  - tomli=2.2.1
  - tqdm=4.67.1
  - tzdata=2025b
  - wheel=0.45.1
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - PyYAML==6.0.2
      - black==25.1.0
      - bson==0.5.10
      - duckdb==1.4.0
      - polars==1.31.0
      - pymongo==4.13.0
      - requests==2.32.4
