[tool.uv.workspace]
members = ["packages/core", "packages/cli"]

[tool.uv.sources]
metahq-core = { workspace = true }
metahq-cli = { workspace = true }

[tool.uv]
dev-dependencies = [
    "pytest>=8.0",
    "pytest-cov",
    "pytest-benchmark",
    "black",
    "isort",
    "flake8",
    "mypy",
    "metahq-cli",
    "metahq-core",
]

