[project]
name = "metahq-core"
dynamic = ["version"]
description = "Core API for the meta-hq CLI."
readme = "README.md"
requires-python = ">=3.12"
authors = [
    {name = "Parker Hicks", email = "parker.hicks@cuanschutz.edu"},
    {name = "Faisal Alquaddoomi", email = "faisal.alquaddoomi@cuanschutz.edu"},
]
keywords = ["Database", "Data Curation", "Public Biomedical Data"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

dependencies = [
    "networkx>=3.0", 
    "numpy>=2.3.0",
    "polars>=1.27.0",
    "pymongo>=4.13.0",
    "pyarrow>=10.0.0",
    "pydantic>=2.0.0",
    "pyyaml>=5.1",
    "duckdb>=1.4.0",
    "rank-bm25>=0.2.2",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-cov",
    "black",
    "isort",
    "flake8",
    "mypy",
    "mkdocs>=1.6.1",
    "pymdown-extensions",
    "mkdocstrings[python]",
    "mkdocs-material",
    "mkdocs-click",
    "vulture",
]

test = [
    "pytest>=8.0",
    "pytest-cov",
    "pytest-benchmark",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/metahq_core/__init__.py"

[tool.hatch.build.targets.sdist]
exclude = ["/.git", "/__pycache__", "*.pyc"]
include = ["src/metahq_core"]

[tool.hatch.build.targets.wheel]
packages = ["src/metahq_core"]

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
